name: home_center_products
packages:
  - './'
  - 'module/domain'
  - 'module/infrastructure'

scripts:
  bootstrap:
    run: dart run melos bootstrap
  fpubget:
    description: "Run flutter pub get in all packages"
    run: dart run melos exec -c 1 -- flutter pub get
  test:
    description: "Run tests in all packages"
    run: dart run melos exec -c 1 -- flutter test
  update-deps:
    description: "Helper: run 'melos exec -- pub upgrade' to update dependencies across packages"
    run: dart run melos exec -c 1 -- dart pub upgrade
